'use client';
import { useEffect, useState, useRef } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, Sun, Moon, Search, ShoppingBag, Menu, Minus, Plus, X } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Slider } from '@/components/ui/slider';
import { motion, MotionConfig, useScroll, useTransform, useReducedMotion } from 'framer-motion';
export type Product = {
    name: string;
    note: string;
    price: number;
    image: string;
    formula: string;
};
export const products: Product[] = [{ name: 'Radiance Serum', note: 'Brighten. Balance. Begin again.', price: 68, image: 'serum', formula: 'A daily serum concept with vitamin C, niacinamide and hyaluronic acid. Apply a few drops to clean skin before your moisturiser.' }, { name: 'Cloud Cream', note: 'A softer kind of hydration.', price: 54, image: 'cream', formula: 'A comforting moisturiser concept with hyaluronic acid and botanical lipids. Smooth gently over face and neck after your serum.' }, { name: 'Botanical Cleanser', note: 'A clean slate. Nothing stripped.', price: 38, image: 'cleanser', formula: 'A gentle cleansing concept for your morning and evening ritual. Massage onto damp skin and rinse with lukewarm water.' }, { name: 'Night Renewal Oil', note: 'Let the evening do its work.', price: 76, image: 'oil', formula: 'A botanical evening oil concept with rosehip and bakuchiol. Press a few drops over moisturiser as the final step of your night ritual.' }];
const links = [['Shop', 'collection'], ['Ritual', 'ritual'], ['Ingredients', 'ingredients'], ['Journal', 'journal'], ['About', 'about']];
const ingredients = [{ name: 'Rosehip', sub: 'Nature’s quiet overachiever.', text: 'Rich in essential fatty acids and naturally occurring antioxidants. A botanical beginning for beautifully considered formulas.', image: 'rosehip' }, { name: 'Hyaluronic acid', sub: 'A little more replenishment.', text: 'A moisture-loving ingredient chosen to support a hydrated, supple feel. Thoughtful science, beautifully simple.', image: 'water' }, { name: 'Niacinamide', sub: 'Balance, beautifully considered.', text: 'A versatile form of vitamin B3, selected for formulas focused on a balanced-looking complexion.', image: 'texture' }, { name: 'Bakuchiol', sub: 'An evening botanical ritual.', text: 'A plant-derived ingredient that brings a considered botanical touch to the evening routine.', image: 'leaves' }, { name: 'Vitamin C', sub: 'A brighter daily ritual.', text: 'An antioxidant ingredient at the heart of our radiance-inspired formula concept.', image: 'rosehip' }];
function Reveal({ children, className = '' }: {
    children: React.ReactNode;
    className?: string;
}) { const reduced = useReducedMotion(); return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .8, ease: [.22, 1, .36, 1] }}>{children}</motion.div>; }
function LinkButton({ href, children, secondary = false }: {
    href: string;
    children: React.ReactNode;
    secondary?: boolean;
}) { return <a onMouseMove={e => { if (matchMedia('(pointer:fine) and (prefers-reduced-motion: no-preference)').matches) {
    const r = e.currentTarget.getBoundingClientRect();
    e.currentTarget.style.transform = `translate(${(e.clientX - r.left - r.width / 2) * .07}px,${(e.clientY - r.top - r.height / 2) * .1}px)`;
} }} onMouseLeave={e => e.currentTarget.style.transform = ''} data-cursor="VIEW" href={href} className={secondary ? 'text-link' : 'button'}>{children}<ArrowUpRight size={16}/></a>; }
function ThemeToggle({ dark, setDark }: {
    dark: boolean;
    setDark: (v: boolean) => void;
}) { return <button className="icon-button theme-toggle" aria-label={`Switch to ${dark ? 'light' : 'dark'} theme`} onClick={() => setDark(!dark)}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button>; }
export function Navbar({ dark, setDark, onSearch, onBag, count }: {
    dark: boolean;
    setDark: (v: boolean) => void;
    onSearch: () => void;
    onBag: () => void;
    count: number;
}) { const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false); useEffect(() => { const fn = () => setScrolled(window.scrollY > 30); window.addEventListener('scroll', fn, { passive: true }); return () => window.removeEventListener('scroll', fn); }, []); return <><header className={`navbar ${scrolled ? 'scrolled' : ''}`}><a className="wordmark" href="#" aria-label="Luméa home">LUMÉA<span>BOTANICAL SKINCARE</span></a><nav className="desktop-nav" aria-label="Main navigation">{links.map(([l, id]) => <a key={id} href={`#${id}`}>{l}</a>)}</nav><div className="nav-actions"><button className="icon-button desktop-tool" aria-label="Search products" onClick={onSearch}><Search size={19}/></button><button className="icon-button desktop-tool bag-button" aria-label={`Shopping bag, ${count} items`} onClick={onBag}><ShoppingBag size={19}/>{count > 0 && <span>{count}</span>}</button><ThemeToggle dark={dark} setDark={setDark}/><button className="icon-button mobile-menu-button" aria-label="Open menu" onClick={() => setMenu(true)}><Menu size={22}/></button></div></header><Dialog open={menu} onOpenChange={setMenu}><DialogContent className="mobile-menu"><DialogHeader><DialogTitle className="wordmark">LUMÉA</DialogTitle><DialogDescription>Skin, elevated by nature.</DialogDescription></DialogHeader><nav>{links.map(([l, id], i) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}><small>0{i + 1}</small>{l}<ArrowUpRight /></a>)}</nav><div className="flex gap-5"><button onClick={() => { setMenu(false); onSearch(); }}>Search</button><button onClick={() => { setMenu(false); onBag(); }}>Shopping bag ({count})</button></div></DialogContent></Dialog></>; }
export function Hero() { const ref = useRef<HTMLElement>(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] }); const y = useTransform(scrollYProgress, [0, 1], ['0%', '22%']); const opacity = useTransform(scrollYProgress, [0, .85], [1, 0]); const reduced = useReducedMotion(); return <section className="hero" ref={ref}><motion.img style={{ y: reduced ? 0 : y }} className="hero-image" src="/images/hero.webp" alt="LUMÉA amber radiance serum on sunlit sculptural stone with olive leaves" fetchPriority="high"/><div className="hero-wash"/><motion.div className="hero-content" style={{ opacity: reduced ? 1 : opacity }}><p className="eyebrow"><span /> NATURE, WITH INTENTION.</p><h1>{['RADIANCE', 'BEGINS', 'WITHIN.'].map((line, i) => <span className="line" key={line}><motion.span initial={reduced ? false : { y: '105%' }} animate={{ y: 0 }} transition={{ delay: .2 + i * .13, duration: 1.1, ease: [.22, 1, .36, 1] }}>{line}</motion.span></span>)}</h1><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .8, duration: .9 }}><p className="hero-description">Botanical intelligence meets<br />modern skincare science.</p><div className="hero-ctas"><LinkButton href="#collection">Explore Collection</LinkButton><LinkButton href="#about" secondary>Our Philosophy</LinkButton></div></motion.div></motion.div><div className="hero-bottom"><a href="#ritual"><ArrowDown size={15}/> SCROLL TO DISCOVER</a><span>SKIN, ELEVATED BY NATURE.</span><span>01 / 05</span></div><div className="hero-caption"><span>THE RADIANCE SERUM</span><small>A daily dose of luminosity. / 30 ml</small></div></section>; }
export function ProductShowcase({ onProduct }: {
    onProduct: (p: Product) => void;
}) { const ref = useRef<HTMLElement>(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'end start'] }); const rotate = useTransform(scrollYProgress, [0, 1], [-4, 4]); return <section id="ritual" className="showcase section-pad" ref={ref}><Reveal className="showcase-intro"><p className="eyebrow">LESS, BUT CONSIDERED.</p><h2>A moment for you.<br /><em>A little more radiance.</em></h2><p>Not another step. A moment to slow down.<br />Essential formulas. Exceptional everyday rituals.</p></Reveal><div className="showcase-layout"><div className="showcase-number">01<span>THE ESSENTIAL</span></div><motion.div className="showcase-photo" style={{ rotate }}><img src="/images/serum.webp" alt="LUMÉA Radiance Serum amber glass dropper bottle" loading="lazy"/><span className="bottle-glint"/></motion.div><Reveal className="showcase-copy"><p className="eyebrow">01 — THE RADIANCE SERUM</p><h3>Your skin.<br /><em>In its best light.</em></h3><p>Concentrated botanical actives designed to restore luminosity and reinforce the skin barrier.</p><button className="text-link" onClick={() => onProduct(products[0])}>Discover Formula <ArrowRight size={18}/></button><div className="formula-notes"><span>VITAMIN C</span><span>NIACINAMIDE</span><span>30 ML / 1 FL OZ</span></div></Reveal></div></section>; }
export function ProductCollection({ onProduct }: {
    onProduct: (p: Product) => void;
}) { return <section id="collection" className="collection section-pad"><Reveal className="section-heading"><div><p className="eyebrow">GOOD SKIN STARTS WITH A RITUAL</p><h2>The daily <em>ritual.</em></h2></div><a href="#products" className="text-link">Meet your essentials <ArrowUpRight size={17}/></a></Reveal><div className="product-grid" id="products">{products.map((p, i) => <Reveal className="product" key={p.name}><button className="product-image" data-cursor="EXPLORE" onClick={() => onProduct(p)}><span className="product-index">0{i + 1} / {i === 0 ? 'THE BESTSELLER' : 'DAILY ESSENTIAL'}</span><img src={`/images/${p.image}.webp`} alt={`LUMÉA ${p.name}`} loading="lazy"/><span className="product-discover">Discover the formula <Plus size={19}/></span></button><div className="product-title"><h3>{p.name}</h3><span>${p.price}</span></div><p>{p.note}</p><button className="product-explore text-link" onClick={() => onProduct(p)}>Explore <ArrowUpRight size={14}/></button></Reveal>)}</div></section>; }
export function IngredientStory() { const ref = useRef<HTMLElement>(null); const [active, setActive] = useState(0); const touchStart = useRef(0); useEffect(() => { const onScroll = () => { if (!ref.current || window.innerWidth < 850)
    return; const r = ref.current.getBoundingClientRect(); setActive(Math.min(4, Math.max(0, Math.floor(-r.top / (r.height - window.innerHeight) * 5)))); }; window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []); return <section id="ingredients" className="ingredient-story" ref={ref}><div className="ingredient-sticky"><div className="ingredient-heading"><p className="eyebrow">ROOTED IN NATURE. REFINED WITH CARE.</p><h2>From earth.<br /><em>Refined by science.</em></h2></div><div className="ingredient-layout"><div className="ingredient-visual" onTouchStart={e => { touchStart.current = e.touches[0].clientX; }} onTouchEnd={e => { const delta = touchStart.current - e.changedTouches[0].clientX; if (Math.abs(delta) > 45)
    setActive(v => Math.max(0, Math.min(4, v + (delta > 0 ? 1 : -1)))); }}>{ingredients.map((item, i) => <img key={i} className={i === active ? 'active' : ''} src={`/images/${item.image}.webp`} alt={item.name + ' ingredient editorial'} loading="lazy"/>)}<span className="image-footnote">THE BOTANICAL INDEX / 0{active + 1}</span></div><div className="ingredient-copy"><div className="ingredient-tabs" role="tablist" aria-label="Ingredients">{ingredients.map((item, i) => <button key={item.name} role="tab" aria-selected={i === active} onClick={() => setActive(i)} className={i === active ? 'active' : ''}>0{i + 1}</button>)}</div><motion.div key={active} initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .5 }}><p className="eyebrow">BOTANICAL INTELLIGENCE / 0{active + 1}</p><h3>{ingredients[active].name}</h3><h4>{ingredients[active].sub}</h4><p>{ingredients[active].text}</p></motion.div><div className="ingredient-progress"><span style={{ width: `${(active + 1) * 20}%` }}/></div><p className="ingredient-scroll">SCROLL TO EXPLORE <ArrowDown size={15}/></p></div></div></div></section>; }
export function BeforeAfter() { const [value, setValue] = useState(50); return <section className="transformation section-pad"><Reveal className="transformation-copy"><p className="eyebrow">A DIFFERENCE YOU CAN FEEL</p><h2>Visible change.<br /><em>Thoughtful<br />formulation.</em></h2><p>A little consistency. A little care.<br />A ritual that puts your skin first.</p><div className="metrics"><div><strong>+32%</strong><span>Hydration</span></div><div><strong>+24%</strong><span>Radiance</span></div><div><strong>92%</strong><span>Softer-looking skin</span></div></div><small className="claim-note">Illustrative brand claims only. Not clinical results. Images are generated demonstrations, not evidence of product efficacy.</small></Reveal><Reveal className="comparison-wrap"><div className="comparison"><img src="/images/after.webp" alt="Illustrative luminous skin texture" loading="lazy"/><img className="before-image" style={{ clipPath: `inset(0 ${100 - value}% 0 0)` }} src="/images/before.webp" alt="Illustrative natural skin texture" loading="lazy"/><div className="comparison-line" style={{ left: `${value}%` }}><span>‹ ›</span></div><span className="before-label">BEFORE</span><span className="after-label">AFTER</span><Slider className="comparison-slider" aria-label="Before and after image comparison" value={[value]} onValueChange={v => setValue(Array.isArray(v) ? v[0] : v)} min={0} max={100}/></div><p className="comparison-caption">A STUDY IN RADIANCE <span>DRAG TO COMPARE ↔</span></p></Reveal></section>; }
export function BrandStory() { return <section id="about" className="brand-story"><img src="/images/leaves.webp" alt="Sunlight through botanical leaves" loading="lazy"/><div className="brand-overlay"/><Reveal><p className="eyebrow">THE LUMÉA PHILOSOPHY</p><h2>Skincare should feel<br />like a <em>ritual.</em></h2><p>Born from the belief that effective skincare can be both<br className="desktop-break"/> scientifically considered and beautifully simple.</p><LinkButton href="#philosophy" secondary>Discover Our Story</LinkButton></Reveal><p id="philosophy" className="brand-bottom">THOUGHTFUL FORMULAS. <span>BEAUTIFUL SIMPLICITY.</span> EVERY SINGLE DAY.</p></section>; }
export function Testimonials() { const [i, setI] = useState(0); const quotes = [['LUMÉA completely changed the way my evening ritual feels.', 'Amelia R.', 'London'], ['A small moment of calm that I look forward to every single day.', 'Sofia M.', 'Copenhagen'], ['Beautifully simple. Just what I wanted my skincare ritual to be.', 'Elena T.', 'Melbourne']]; return <section className="testimonials section-pad"><p className="eyebrow">WORDS FROM THE RITUAL</p><p className="stars" aria-label="5 stars">★★★★★</p><motion.blockquote key={i} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .6 }}>“{quotes[i][0]}”</motion.blockquote><p className="quote-author">{quotes[i][1]} <span>— {quotes[i][2]}</span></p><div className="quote-controls">{quotes.map((_, n) => <button key={n} className={i === n ? 'active' : ''} onClick={() => setI(n)} aria-label={`Read testimonial ${n + 1}`} aria-pressed={i === n}/>)}</div><small>Sample testimonials for this fictional brand.</small></section>; }
export const articles = [{ title: 'The Art of a Skin Ritual', image: 'leaves', category: 'RITUALS', body: 'Make a little space for yourself. A daily skincare ritual can be as simple as cleansing gently, applying a moisturiser and giving each step your attention. In the morning, finish with sunscreen. Start small and let your routine become a comfortable part of your day.' }, { title: 'Understanding Your Skin Barrier', image: 'before', category: 'SKIN NOTES', body: 'Your skin’s outer layer helps retain moisture and protect against the environment. A gentle routine gives it room to do its work. Avoid over-cleansing, introduce products gradually, and choose a moisturiser that feels comfortable. Persistent irritation deserves guidance from a qualified professional.' }, { title: 'Botanical Ingredients Worth Knowing', image: 'rosehip', category: 'THE INGREDIENT EDIT', body: 'Botanicals bring a rich vocabulary to skincare. Rosehip oil is known for its fatty acid content; bakuchiol is a plant-derived ingredient used in evening formulas. The complete formulation matters more than a single celebrated ingredient. Patch test new products and choose what suits your skin.' }];
export function Journal({ onArticle }: {
    onArticle: (i: number) => void;
}) { return <section id="journal" className="journal section-pad"><Reveal className="section-heading"><div><p className="eyebrow">A LITTLE KNOWLEDGE. A DEEPER RITUAL.</p><h2>The <em>journal.</em></h2></div><span className="journal-note">Notes on skin & slow living.</span></Reveal><div className="journal-grid">{articles.map((a, i) => <Reveal key={a.title}><button className="journal-card" onClick={() => onArticle(i)} data-cursor="EXPLORE"><div className="journal-image"><img src={`/images/${a.image}.webp`} alt={a.title} loading="lazy"/></div><p className="eyebrow">{a.category}<span>3 MIN READ</span></p><h3>{a.title}<ArrowUpRight size={19}/></h3><span className="text-link">Read the story</span></button></Reveal>)}</div></section>; }
export function Newsletter() { const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); return <section className="newsletter section-pad"><div><p className="eyebrow">LET GOOD THINGS FIND YOU</p><h2>A little more <em>glow.</em></h2><p>Join the LUMÉA journal for rituals, ingredients, and skincare notes.</p></div><form onSubmit={e => { e.preventDefault(); setSent(true); }}><div className="email-input"><input aria-label="Your email address" type="email" placeholder="Your email address" value={email} onChange={e => { setEmail(e.target.value); setSent(false); }} required/><button type="submit" aria-label="Subscribe">Subscribe <ArrowRight size={19}/></button></div><p role="status">{sent ? 'Thank you for your interest. This concept site does not collect or send emails.' : 'Thoughtful notes, occasionally. No noise.'}</p></form></section>; }
export function Footer({ onInfo }: {
    onInfo: (s: string) => void;
}) { return <footer className="footer section-pad"><div className="footer-top"><div><a href="#" className="wordmark">LUMÉA</a><p>SKIN, ELEVATED BY NATURE.</p></div><nav aria-label="Footer navigation">{links.map(([l, id]) => <a key={id} href={`#${id}`}>{l}</a>)}<button onClick={() => onInfo('Contact')}>Contact</button></nav><nav aria-label="Social links">{['Instagram', 'Pinterest', 'TikTok'].map(x => <button key={x} onClick={() => onInfo(x)}>{x}<ArrowUpRight size={13}/></button>)}</nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} LUMÉA. A fictional skincare concept.</span><div>{['Privacy', 'Terms', 'Shipping', 'Returns'].map(x => <button key={x} onClick={() => onInfo(x)}>{x}</button>)}</div><a href="#">BACK TO TOP ↑</a></div></footer>; }
export function Cursor() { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!matchMedia('(pointer:fine)').matches || matchMedia('(prefers-reduced-motion: reduce)').matches)
    return; const fn = (e: MouseEvent) => { if (!ref.current)
    return; ref.current.style.transform = `translate(${e.clientX}px,${e.clientY}px)`; const target = (e.target as HTMLElement).closest('[data-cursor]'); ref.current.dataset.active = target ? 'true' : 'false'; ref.current.textContent = target?.getAttribute('data-cursor') || ''; }; window.addEventListener('mousemove', fn); return () => window.removeEventListener('mousemove', fn); }, []); return <div ref={ref} className="custom-cursor" aria-hidden="true"/>; }
